services:
  nginx:
    container_name: nginx
    volumes:
      - website_data:/var/www/djangoserver
    networks:
      - transcendence
    depends_on:
      - djangoserver
    build: requirements/nginx
    ports:
      - "443:443"
    restart: always 

  djangoserver:
    container_name: djangoserver
    volumes:
      - website_data:/var/www/djangoserver
    networks:
      - transcendence
    build: requirements/djangoserver
    restart: always 
    ports:
      - "9000:9000"

volumes:
  website_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '~/PTME_data'

networks:
  transcendence:
    driver: bridge
