services:
  nginx:
    container_name: nginx
    volumes:
      - website_data:/var/www/djangoserver
    networks:
      - transcendence
    depends_on:
      - djangoserver
    build: requirements/nginx
    ports:
      - "443:443"
    restart: always 

  djangoserver:
    container_name: djangoserver
    volumes:
      - website_data:/var/www/djangoserver
    networks:
      - transcendence
    build:
      context: requirements/djangoserver
      args:
        DB_NAME: ${DB_NAME}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_HOST: ${DB_HOST}
    restart: always 
    ports:
      - "9000:9000"

  postgresql:
    container_name: postgresql
    env_file: .env
    build: 
      context: requirements/postgresql
      args:
        DB_NAME: ${DB_NAME}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
#    volumes:
#      - website_data:/var/www/djangoserver
    networks:
      - transcendence
    restart: always 
    ports:
      - "5432:5432"

volumes:
  website_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '~/PTME_data'

networks:
  transcendence:
    driver: bridge
